# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8

      # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: core_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_HOST: %
          MYSQL_USER: root
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/go-xorm/core
    steps:
      - checkout

          # specify any bash command here prefixed with `run: `
      - run: mysql -u root -e "CREATE DATABASE core_test DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci"
      - run: go get -u github.com/golang/lint/golint
      - run: go get -u github.com/wadey/gocovmerge
      - run: golint ./...
      - run: go get -t -d -v ./...
      - run: go test -v -race -coverprofile=coverage-1.txt -covermode=atomic
      - run: go test -v -race --dbtype=sqlite3 -coverprofile=coverage-2.txt -covermode=atomic
      - run: gocovmerge coverage-1.txt coverage-2.txt > coverage.txt
      - run: bash <(curl -s https://codecov.io/bash)